<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZucchiCMS\Module'                        => __DIR__ . '/Module.php',
    'ZucchiCMS\Controller\SkeletonController' => __DIR__ . '/src/ZucchiCMS/Controller/SkeletonController.php',

    // tests
    'ZucchiCMSTest\Framework\TestCase'        => __DIR__ . '/tests/ZucchiCMS/Framework/TestCase.php',
    'ZucchiCMSTest\SampleTest'                => __DIR__ . '/tests/ZucchiCMS/SampleTest.php',
);